"""phase1_sessions

Revision ID: 20260927_0002
Revises: 
Create Date: 2026-09-27 20:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20260927_0002'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_device_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_device_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('pairing_code', sa.String(length=6), nullable=True),
    sa.Column('pairing_attempts', sa.Integer(), nullable=False),
    sa.Column('max_pairing_attempts', sa.Integer(), nullable=False),
    sa.Column('pairing_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('files_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['sender_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_sessions_pairing_code'), 'transfer_sessions', ['pairing_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_sessions_pairing_code'), table_name='transfer_sessions')
    op.drop_table('transfer_sessions')
    # ### end Alembic commands ###
